---
version: "3.4"
services:
  signalling:
    build:
      context: ../
      dockerfile: ./SignallingWebServer/Dockerfile
    image: signalling
    init: true
    network_mode: "host"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80"]
        interval: 10s
        timeout: 5s
        retries: 3
        start_period: 30s
        start_interval: 5s # only supported on docker engine 25+

  tester:
    build:
      context: ../
      dockerfile: ./SS_Test/Dockerfile
    image: signalling_tester
    network_mode: "host"
    depends_on:
      signalling:
        condition: service_healthy

