name: Publish the Signalling Server container image for Unreal Engine 5.1

on:
  push:
    branches: ['UE5.1']

jobs:
  signalling-server-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push the Signalling Server container image for Unreal Engine 5.1
        uses: docker/build-push-action@v3
        with:
          context: ./SignallingWebServer
          tags: 'ghcr.io/epicgames/pixel-streaming-signalling-server:5.1'
          push: true
